# Generated by Django 3.2 on 2021-06-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
