# Generated by Django 3.2 on 2021-06-18 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(null=True, verbose_name=datetime.date(2021, 6, 18)),
        ),
    ]
