# Generated by Django 3.2 on 2021-06-18 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_completed',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
