# Generated by Django 3.2 on 2021-06-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_task_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='archieve',
            field=models.BooleanField(default=False),
        ),
    ]
