# Generated by Django 3.2 on 2021-06-21 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_task_archieve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='archieve',
        ),
    ]
