# Generated by Django 3.2 on 2021-06-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_task_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_priority',
            field=models.CharField(default='medium', max_length=200),
            preserve_default=False,
        ),
    ]
