# Generated by Django 3.2 on 2021-06-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_task_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_priority',
            field=models.CharField(choices=[('MEDIUM', 'Medium'), ('HIGH', 'High'), ('LOW', 'Low')], max_length=200),
        ),
    ]
